DATA: Created IGenericRepository Interface.
dotnetuz-intership/BelissimoCloneWpf pull request #29
Opened 2023-02-11 12:30 UTC by khabibulladev

Created IGenericRepository Interface Inside IRepositories Folder.

2023-02-11 12:30 UTC, khabibulladev commented
Closes #29

2023-02-11 12:56 UTC, MuhammadKasimov requested changes

2023-02-11 12:56 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/IRepositories/IGenericRepository.cs
> +    {
Make Generic work only with Auditable

2023-02-12 07:24 UTC, khabibulladev commented
Made Generic work only with Auditable

2023-02-12 08:55 UTC, MuhammadKasimov commented
Man what are you doing!?

2023-02-12 08:57 UTC, MuhammadKasimov requested changes
It had to be 
public interface IGenericRepository<T> where T : Auditable

2023-02-12 09:39 UTC, merged