DATA: Corrected GenericRepository Class
dotnetuz-intership/BelissimoCloneWpf pull request #50
Opened 2023-02-15 19:40 UTC by Dilshod-Abdijabbarov

DATA: Corrected GenericRepository Class

2023-02-15 19:42 UTC, Dilshod-Abdijabbarov commented
DATA: Corrected GenericRepository Class

2023-02-16 13:09 UTC, MuhammadKasimov requested changes
Make new method which saves changes

2023-02-16 13:09 UTC, MuhammadKasimov commented
Create Issue!

2023-02-16 14:28 UTC, Dilshod-Abdijabbarov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            _dbContext.SaveChangesAsync();
Whether to add the await keyword to the code

2023-02-16 14:41 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            _dbContext.SaveChangesAsync();
noo

2023-02-16 14:42 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            _dbContext.SaveChangesAsync();
create new method to save changes reomve save changes from Create Update Delete

2023-02-16 16:45 UTC, MuhammadKasimov requested changes

2023-02-16 16:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            SaveChangesAsync();
we will use it in service layer just remove this line

2023-02-16 16:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +                SaveChangesAsync();
the same
remove here

2023-02-16 16:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +        public async Task SaveChangesAsync()
make it return ValueTask instead of Task

2023-02-16 16:47 UTC, MuhammadKasimov commented
Issue!

2023-02-17 10:45 UTC, MuhammadKasimov requested changes

2023-02-17 10:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> -            return (_dbContext.Set<T>().Update(entity)).Entity;
Crete DbSet field instead

2023-02-17 10:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            await dbContext.SaveChangesAsync();
Make it lambda

2023-02-17 10:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            return (await dbContext.Set<T>().AddAsync(entity)).Entity;
lmbda

2023-02-17 10:45 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +            return dbContext.Set<T>().Where(expression);
use include
and isTracking

2023-02-17 17:26 UTC, Dilshod-Abdijabbarov commented
Create lambda expression methods

2023-02-18 11:07 UTC, MuhammadKasimov requested changes

2023-02-18 11:07 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +        public GenericRepository(BelissimoDbContext dbcontext)
not dbcontext
it should be dbContext

2023-02-18 11:07 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +               return false;
where is if?

2023-02-18 11:07 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
> +                foreach (var includ in includes)
include* 
not includ

2023-02-18 13:41 UTC, Dilshod-Abdijabbarov commented
Changed GetAll and DeleteAsync methods

2023-02-18 13:58 UTC, merged