SERVICE: Attributes foldier and inside it UserPassword class created.
dotnetuz-intership/BelissimoCloneWpf pull request #66
Opened 2023-02-20 19:18 UTC by OlimSadullaev

2023-02-20 19:19 UTC, OlimSadullaev commented
UserPassword created

2023-02-20 19:20 UTC, OlimSadullaev commented
Created

2023-02-21 11:23 UTC, MuhammadKasimov requested changes

2023-02-21 11:23 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/Attributes/UserPassword.cs
> +                        password.Any(c => char.IsLetter(c));
override IsValid which returns ValidationResult

2023-02-21 12:21 UTC, ShohruhUzDev commented
Tag issue

2023-02-22 10:16 UTC, MuhammadKasimov requested changes

2023-02-22 10:16 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/Attributes/UserPassword.cs
> +                return new ValidationResult("password must be at least one number and at least one letter and number of characters more or equal to 8");
Password not password

2023-02-22 12:16 UTC, OlimSadullaev commented on BelissimoCloneWPF.Service/Attributes/UserPassword.cs
> +                return new ValidationResult("password must be at least one number and at least one letter and number of characters more or equal to 8");
Changes Accomplished from password to Password

2023-02-22 12:20 UTC, merged