SERVICE: Created IOrderService and OrderService
dotnetuz-intership/BelissimoCloneWpf pull request #91
Opened 2023-03-01 07:42 UTC by AbbosHaydarov

Closes #82

2023-03-01 09:23 UTC, MuhammadKasimov requested changes

2023-03-01 09:23 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForViewDTO.cs
> +}
add id property

2023-03-01 09:23 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForUpdateDTO.cs
> +}
Use Creation instead
remove this class

2023-03-01 09:23 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/Services/Orders/OrderService.cs
> +            await orderRepository.SaveChangesAsync();
chack for basket existance

2023-03-01 09:23 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/Services/Orders/OrderService.cs
> +
the same with basket

2023-03-01 10:46 UTC, AbbosHaydarov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForViewDTO.cs
> +}
Added Id Property

2023-03-01 10:46 UTC, AbbosHaydarov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForUpdateDTO.cs
> +}
Removed OrderForUpdateDTO and used OrderForCreationDTO

2023-03-01 10:56 UTC, AbbosHaydarov commented on BelissimoCloneWPF.Service/Services/Orders/OrderService.cs
> +            await orderRepository.SaveChangesAsync();
Wrote checking BasketId

2023-03-01 12:10 UTC, MuhammadKasimov requested changes
have you removed OrderForUpdateDTO class

2023-03-01 12:10 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForViewDTO.cs
> +        public int OrderId { get; set; }
name it id

2023-03-01 13:51 UTC, AbbosHaydarov commented on BelissimoCloneWPF.Service/Services/Orders/OrderService.cs
> +
Corrected mistake

2023-03-06 18:01 UTC, AbbosHaydarov commented on BelissimoCloneWPF.Service/DTOs/Orders/OrderForViewDTO.cs
> +        public int OrderId { get; set; }
changed

2023-03-06 18:02 UTC, closed without merging