SERVICE: Created interface IAttachmentService and class AttachmentService
dotnetuz-intership/BelissimoCloneWpf pull request #96
Opened 2023-03-02 10:43 UTC by AbbosJaan

Closes #95

2023-03-06 14:02 UTC, MuhammadKasimov requested changes

2023-03-06 14:02 UTC, MuhammadKasimov commented on BelissimoCloneWPF.Service/Services/Attachment/AttachmentService.cs
>          public async ValueTask<Attachments> CreateAsync(AttachmentForCreationDTO attachemntForCreationDTO)
rename `Attachments` to `Attachment`

2023-03-26 06:01 UTC, abbosbeck commented on BelissimoCloneWPF.Service/Interfaces/Attachment/IAttachmentService.cs
> +        ValueTask<Attachments> CreateAsync(AttachmentForCreationDTO attachemntForCreationDTO);
But our entity named "Attachments"

2023-03-26 06:11 UTC, abbosbeck commented on BelissimoCloneWPF.Service/Services/Attachment/AttachmentService.cs
>          public async ValueTask<Attachments> CreateAsync(AttachmentForCreationDTO attachemntForCreationDTO)
our `Attachment` Entity is named `Attachments`

2023-03-27 15:13 UTC, merged